[libs]
dest = "$BOARDROOT/lib"
folders = [
"$PROJROOT/libpython/MyState",
"$PROJROOT/lib_cktpy/EasyCktIO",
]

[project]
dest = "$BOARDROOT"
files = [
"$THISPKG/StateDef.py",
"$THISPKG/StateReact.py",
"$THISPKG/Opt_RotEncoder.py",
"$THISPKG/main.py",
]

[libs.CPYBUNDLE]
dest = "$BOARDROOT/lib"
folders = [
"$SRCLIB/adafruit_seesaw",
]