[modules.CPYBUNDLE]
dest = "$BOARDROOT/lib"
folders = [
"$LIBPATH_CPYBUNDLE/adafruit_seesaw",
]

[modules]
dest = "$BOARDROOT/lib"
folders = [
"$LIBROOT/libpython/MyState",
"$LIBROOT/lib_cktpy/EasyCktIO",
]

[package]
dest = "$BOARDROOT"
files = [
"$THISPKG/StateDef.py",
"$THISPKG/StateReact.py",
"$THISPKG/Opt_RotEncoder.py",
"$THISPKG/main.py",
]
