[modules.CPYBUNDLE]
dest = "$BOARDROOT/lib"
files = [
"$LIBPATH_CPYBUNDLE/neopixel.mpy",
]

[modules]
dest = "$BOARDROOT/lib"
folders = [
"$LIBROOT/libpython/MyState",
"$LIBROOT/lib_cktpy/EasyCktIO",
]

[package]
dest = "$BOARDROOT"
files = [
"$THISPKG/main.py",
]
